version: "3.8"

services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  node-service:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_DATABASE: ${MYSQL_DATABASE}
      DB_USERNAME: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
    expose:
      - "3000" # Expose port to other services in the same network
    depends_on:
      - db
    networks:
      - app-network
    deploy:
      replicas: 3 # Scaling the service to 3 instances

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node-service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
